/**
 * Editor enemy placement — maps palette item IDs to enemy/area data records.
 * Called by editorTools.ts placeAtCursor() for all enemy and area palette items.
 */

import { EditorState, EditorRoomData, PaletteItem, allocateUid } from './editorState';

/**
 * Handles placement of enemy and grasshopper-area palette items.
 * Mutates room.enemies / room.grasshopperAreas in place.
 * Returns true if the item was handled (was a known enemy or area type),
 * false if the caller should continue checking other item types.
 */
export function placeEnemyAtCursor(
  state: EditorState,
  room: EditorRoomData,
  item: PaletteItem,
  bx: number,
  by: number,
): boolean {
  if (item.id === 'enemy_rolling') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Physical'],
      particleCount: 18,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 1,
      rollingEnemySpriteIndex: 1,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_flying_eye') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Wind'],
      particleCount: 16,
      isBossFlag: 0,
      isFlyingEyeFlag: 1,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_rock_elemental') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Earth'],
      particleCount: 20,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 1,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_slime') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Nature'],
      particleCount: 8,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 1,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_slime_large') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Nature'],
      particleCount: 16,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 1,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_wheel') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Physical'],
      particleCount: 12,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 1,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_beetle') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Physical'],
      particleCount: 8,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 1,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_water_bubble') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Water'],
      particleCount: 12,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 1,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_ice_bubble') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Ice'],
      particleCount: 10,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 1,
      isIceBubbleFlag: 1,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_square_stampede') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Void'],
      particleCount: 5,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 1,
    });
  } else if (item.id === 'enemy_golden_mimic') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Physical'],
      particleCount: 20,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isGoldenMimicFlag: 1,
      isGoldenMimicYFlippedFlag: 0,
    });
  } else if (item.id === 'enemy_golden_mimic_xy') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Physical'],
      particleCount: 20,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isGoldenMimicFlag: 1,
      isGoldenMimicYFlippedFlag: 1,
    });
  } else if (item.id === 'enemy_bee_swarm') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Physical'],
      particleCount: 10,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 1,
    });
  } else if (item.id === 'grasshopper_area') {
    room.grasshopperAreas.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      wBlock: 4,
      hBlock: 4,
      count: 4,
    });
  } else if (item.id === 'firefly_area') {
    if (!room.fireflyAreas) room.fireflyAreas = [];
    room.fireflyAreas.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      wBlock: 4,
      hBlock: 4,
      count: 4,
    });
  } else {
    return false;
  }
  return true;
}
