/**
 * Editor enemy placement — maps palette item IDs to enemy/area data records.
 * Called by editorTools.ts placeAtCursor() for all enemy and area palette items.
 */

import { EditorState, EditorRoomData, PaletteItem, allocateUid } from './editorState';
import { MAX_SHADOW_ENEMIES } from '../sim/clusters/shadowEnemyConfig';
import { MAX_NEEDLE_URCHINS } from '../sim/clusters/needleUrchinConfig';
import { canAddLimitedEnemy } from './editorEnemyCapacity';

function warnEditorCapacity(enemyType: 'Shadow' | 'Needle Urchin', limit: number): void {
  if (import.meta.env?.DEV === true) {
    console.warn(`[editorEnemyPlacer] ${enemyType} limit reached; maximum per room is ${limit}.`);
  }
}

/**
 * Handles placement of enemy and grasshopper-area palette items.
 * Mutates room.enemies / room.grasshopperAreas in place.
 * Returns true if the item was handled (was a known enemy or area type),
 * false if the caller should continue checking other item types.
 */
export function placeEnemyAtCursor(
  state: EditorState,
  room: EditorRoomData,
  item: PaletteItem,
  bx: number,
  by: number,
): boolean {
  if (item.id === 'enemy_rolling') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 18,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 1,
      rollingEnemySpriteIndex: 1,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_flying_eye') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Wind'],
      particleCount: 16,
      isBossFlag: 0,
      isFlyingEyeFlag: 1,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_rock_elemental') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Earth'],
      particleCount: 20,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 1,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_grapple_hunter') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 18,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 1,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_slime') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Nature'],
      particleCount: 8,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 1,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_slime_large') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Nature'],
      particleCount: 16,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 1,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_wheel') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 12,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 1,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_beetle') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 8,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 1,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_water_bubble') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Water'],
      particleCount: 12,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 1,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_ice_bubble') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Ice'],
      particleCount: 10,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 1,
      isIceBubbleFlag: 1,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'enemy_square_stampede') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Void'],
      particleCount: 5,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 1,
    });
  } else if (item.id === 'enemy_shadow' || item.id === 'enemy_needle_urchin') {
    const isShadow = item.id === 'enemy_shadow';
    const enemyType = isShadow ? 'shadow' : 'needleUrchin';
    const limit = isShadow ? MAX_SHADOW_ENEMIES : MAX_NEEDLE_URCHINS;
    if (!canAddLimitedEnemy(room, enemyType)) {
      warnEditorCapacity(isShadow ? 'Shadow' : 'Needle Urchin', limit);
      return true;
    }
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: [isShadow ? 'Void' : 'Golden'],
      particleCount: isShadow ? 1 : 3,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isShadowEnemyFlag: isShadow ? 1 : 0,
      isNeedleUrchinFlag: isShadow ? 0 : 1,
    });
  } else if (item.id === 'enemy_slime_snail') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Nature'],
      particleCount: 2,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isSlimeSnailFlag: 1,
      slimeSnailSurfaceSideIndex: 0,
      slimeSnailClockwiseFlag: 1,
    });
  } else if (item.id === 'enemy_golden_mimic') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 20,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isGoldenMimicFlag: 1,
      isGoldenMimicYFlippedFlag: 0,
    });
  } else if (item.id === 'enemy_golden_mimic_xy') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 20,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isGoldenMimicFlag: 1,
      isGoldenMimicYFlippedFlag: 1,
    });
  } else if (item.id === 'enemy_bee_swarm') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 10,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 1,
    });
  } else if (item.id === 'enemy_web_spider') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 6,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 1,
    });
  } else if (item.id === 'enemy_dust_constellation') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 6,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 1,
      isDustConstellationLargeFlag: 0,
    });
  } else if (item.id === 'enemy_dust_constellation_large') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 10,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 1,
      isDustConstellationLargeFlag: 1,
    });
  } else if (item.id === 'enemy_orbital_dust_core') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 6,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 1,
      isOrbitalDustCoreLargeFlag: 0,
    });
  } else if (item.id === 'enemy_orbital_dust_core_large') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 10,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 1,
      isOrbitalDustCoreLargeFlag: 1,
    });
  } else if (item.id === 'enemy_dust_block_mimic') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 1,
      isDustBlockMimicLargeFlag: 0,
    });
  } else if (item.id === 'enemy_dust_block_mimic_large') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 1,
      isDustBlockMimicLargeFlag: 1,
    });
  } else if (item.id === 'enemy_stick_blade_architect') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 0,
      isDustBlockMimicLargeFlag: 0,
      isStickBladeArchitectFlag: 1,
      isStickBladeArchitectLargeFlag: 0,
    });
  } else if (item.id === 'enemy_stick_blade_architect_large') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 0,
      isDustBlockMimicLargeFlag: 0,
      isStickBladeArchitectFlag: 1,
      isStickBladeArchitectLargeFlag: 1,
    });
  } else if (item.id === 'enemy_void_singularity') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 0,
      isDustBlockMimicLargeFlag: 0,
      isStickBladeArchitectFlag: 0,
      isStickBladeArchitectLargeFlag: 0,
      isVoidSingularityFlag: 1,
      isVoidSingularityPairFlag: 0,
    });
  } else if (item.id === 'enemy_void_singularity_pair') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 0,
      isDustBlockMimicLargeFlag: 0,
      isStickBladeArchitectFlag: 0,
      isStickBladeArchitectLargeFlag: 0,
      isVoidSingularityFlag: 1,
      isVoidSingularityPairFlag: 1,
    });
  } else if (item.id === 'enemy_dust_leech') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 0,
      isDustBlockMimicLargeFlag: 0,
      isStickBladeArchitectFlag: 0,
      isStickBladeArchitectLargeFlag: 0,
      isVoidSingularityFlag: 0,
      isVoidSingularityPairFlag: 0,
      isDustLeechFlag: 1,
    });
    return true;
  } else if (item.id === 'enemy_momentum_turret') {
    room.enemies.push({
      uid: allocateUid(state), xBlock: bx, yBlock: by,
      kinds: ['Golden'], particleCount: 0, isBossFlag: 0,
      isFlyingEyeFlag: 0, isRollingEnemyFlag: 0, rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0, isRadiantTetherFlag: 0, isRadiantWebFlag: 0, isGrappleHunterFlag: 0,
      isSlimeFlag: 0, isLargeSlimeFlag: 0, isWheelEnemyFlag: 0, isBeetleFlag: 0,
      isBubbleEnemyFlag: 0, isIceBubbleFlag: 0, isSquareStampedeFlag: 0,
      isMomentumTurretFlag: 1,
      momentumTurretFacingIndex: (state.placementRotationSteps % 4) as 0 | 1 | 2 | 3,
    });
    return true;
  } else if (item.id === 'enemy_grid_snake') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 0,
      isDustBlockMimicLargeFlag: 0,
      isStickBladeArchitectFlag: 0,
      isStickBladeArchitectLargeFlag: 0,
      isVoidSingularityFlag: 0,
      isVoidSingularityPairFlag: 0,
      isDustLeechFlag: 0,
      isGridBlockEnemyFlag: 0,
      isGridSnakeEnemyFlag: 1,
      gridSnakeLength: 4,
    });
    return true;
  } else if (
    item.id === 'enemy_grid_block_1x1_slow'   ||
    item.id === 'enemy_grid_block_1x1_medium' ||
    item.id === 'enemy_grid_block_1x1_fast'   ||
    item.id === 'enemy_grid_block_2x2_slow'   ||
    item.id === 'enemy_grid_block_2x2_medium' ||
    item.id === 'enemy_grid_block_2x2_fast'
  ) {
    const sizeIndex: 0 | 1  = item.id.includes('2x2') ? 1 : 0;
    const speedIndex: 0 | 1 | 2 = item.id.endsWith('_fast') ? 2
                                 : item.id.endsWith('_medium') ? 1 : 0;
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: 0,
      isBossFlag: 0,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
      isDustConstellationFlag: 0,
      isDustConstellationLargeFlag: 0,
      isOrbitalDustCoreFlag: 0,
      isOrbitalDustCoreLargeFlag: 0,
      isDustBlockMimicFlag: 0,
      isDustBlockMimicLargeFlag: 0,
      isStickBladeArchitectFlag: 0,
      isStickBladeArchitectLargeFlag: 0,
      isVoidSingularityFlag: 0,
      isVoidSingularityPairFlag: 0,
      isDustLeechFlag: 0,
      isGridBlockEnemyFlag: 1,
      gridBlockSizeIndex: sizeIndex,
      gridBlockSpeedIndex: speedIndex,
    });
    return true;
  } else if (item.id === 'enemy_radiant_tether') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Holy'],
      particleCount: 16,
      isBossFlag: 1,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 1,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
    });
  } else if (item.id === 'enemy_radiant_web') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Holy'],
      particleCount: 16,
      isBossFlag: 1,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 1,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
    });
  } else if (item.id === 'enemy_crimson_wizard') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Fire'],
      particleCount: 24,
      isBossFlag: 1,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isCrimsonWizardFlag: 1,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
    });
  } else if (item.id === 'enemy_herald') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Fire'],
      particleCount: 20,
      isBossFlag: 1,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isCrimsonWizardFlag: 0,
      isHeraldFlag: 1,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
    });
  } else if (item.id === 'enemy_ice_wizard') {
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Ice'],
      particleCount: 0,
      isBossFlag: 1,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isCrimsonWizardFlag: 0,
      isHeraldFlag: 0,
      isIceWizardFlag: 1,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
      isBeeSwarmFlag: 0,
      isWebSpiderFlag: 0,
    });
  } else if (item.id === 'enemy_bald_roller' ||
             item.id === 'enemy_slime_cube' ||
             item.id === 'enemy_tripod_spinner' ||
             item.id === 'enemy_psi_sky_ranger' ||
             item.id === 'enemy_glyph_gyre' ||
             item.id === 'enemy_time_wraith' ||
             item.id === 'enemy_realm_guardian' ||
             item.id === 'enemy_tricyclic_slasher' ||
             item.id === 'enemy_sand_block' ||
             item.id === 'enemy_sand_wanderer' ||
             item.id === 'enemy_aleph_glyph' ||
             item.id === 'enemy_shin_glyph' ||
             item.id === 'enemy_zeta_glyph' ||
             item.id === 'enemy_xi_glyph' ||
             item.id === 'enemy_theta_harmonic') {
    const STICK_RPG_MAP: Record<string, string> = {
      enemy_bald_roller: 'baldRoller',
      enemy_slime_cube: 'slimeCube',
      enemy_tripod_spinner: 'tripodSpinner',
      enemy_psi_sky_ranger: 'psiSkyRanger',
      enemy_glyph_gyre: 'glyphGyre',
      enemy_time_wraith: 'timeWraith',
      enemy_realm_guardian: 'realmGuardian',
      enemy_tricyclic_slasher: 'tricylicSlasher',
      enemy_sand_block: 'sandBlock',
      enemy_sand_wanderer: 'sandWanderer',
      enemy_aleph_glyph: 'alephGlyph',
      enemy_shin_glyph: 'shinGlyph',
      enemy_zeta_glyph: 'zetaGlyph',
      enemy_xi_glyph: 'xiGlyph',
      enemy_theta_harmonic: 'thetaHarmonic',
    };
    const kind = STICK_RPG_MAP[item.id];
    const isBoss: 0 | 1 = kind === 'realmGuardian' ? 1 : 0;
    room.enemies.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      kinds: ['Golden'],
      particleCount: isBoss === 1 ? 60 : 20,
      isBossFlag: isBoss,
      stickRpgEnemyKind: kind,
      isFlyingEyeFlag: 0,
      isRollingEnemyFlag: 0,
      rollingEnemySpriteIndex: 0,
      isRockElementalFlag: 0,
      isRadiantTetherFlag: 0,
      isRadiantWebFlag: 0,
      isGrappleHunterFlag: 0,
      isSlimeFlag: 0,
      isLargeSlimeFlag: 0,
      isWheelEnemyFlag: 0,
      isBeetleFlag: 0,
      isBubbleEnemyFlag: 0,
      isIceBubbleFlag: 0,
      isSquareStampedeFlag: 0,
    });
  } else if (item.id === 'grasshopper_area') {
    room.grasshopperAreas.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      wBlock: 4,
      hBlock: 4,
      count: 4,
    });
  } else if (item.id === 'firefly_area') {
    if (!room.fireflyAreas) room.fireflyAreas = [];
    room.fireflyAreas.push({
      uid: allocateUid(state),
      xBlock: bx,
      yBlock: by,
      wBlock: 4,
      hBlock: 4,
      count: 4,
    });
  } else {
    return false;
  }
  return true;
}
