/**
 * Canonical 8-world node-graph map topology ported from STICK-RPG.
 *
 * Replaces the flat grid with an 8-world radial topology branching from the
 * central World Tree hub (0.5, 0.5) outward across 5 stages per world, ending
 * at each world's Stage 5 Boss Arena.
 */

import { LevelTheme } from './levelDef';

export interface WorldMapNodeDef {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly stageCode: string;
  readonly worldNumber: number;
  readonly stageNumber: number;
  readonly x: number;
  readonly y: number;
  readonly theme: LevelTheme;
  readonly order?: string;
  readonly branch: string;
  readonly branchStep: number;
  readonly parent?: string;
  readonly isBoss: boolean;
  readonly optional?: boolean;
  readonly standalone?: boolean;
  readonly requiresStages?: readonly string[];
  readonly bossName?: string;
  readonly bossHp?: number;
  readonly bossAttack?: number;
  readonly bossDefense?: number;
}

export interface WorldMapLinkDef {
  readonly fromId: string;
  readonly toId: string;
}

/** The central World Tree hub. */
export const WORLD_TREE_HUB_NODE: WorldMapNodeDef = {
  id: 'worldTree',
  name: 'World Tree',
  description: 'A cozy home base nestled against the massive trunk. Venture across the branches to reach the outer domains.',
  stageCode: 'HUB',
  worldNumber: 0,
  stageNumber: 0,
  x: 0.5,
  y: 0.5,
  theme: 'physical',
  order: 'H',
  branch: 'hub',
  branchStep: 0,
  isBoss: false,
  optional: true,
  standalone: true,
};

/** Canonical 40 mainline stages (8 worlds × 5 stages) ported from STICK-RPG. */
export const WORLD_MAP_NODES: readonly WorldMapNodeDef[] = [
  // World 1: Verdant Canopy (light/wind)
  {
    id: 'world1Stage1',
    name: 'Verdant Foothills',
    description: 'Mossy bluffs mark the start of the ascent.',
    stageCode: '1-1',
    worldNumber: 1,
    stageNumber: 1,
    x: 0.53,
    y: 0.41,
    theme: 'physical',
    branch: 'world1',
    branchStep: 1,
    parent: 'worldTree',
    isBoss: false,
  },
  {
    id: 'world1Stage2',
    name: 'Emerald Thicket',
    description: 'Dense canopy weaves through twisting branches.',
    stageCode: '1-2',
    worldNumber: 1,
    stageNumber: 2,
    x: 0.56,
    y: 0.32,
    theme: 'physical',
    branch: 'world1',
    branchStep: 2,
    parent: 'world1Stage1',
    isBoss: false,
  },
  {
    id: 'world1Stage3',
    name: 'Skyward Boughs',
    description: 'High winds whip across the upper branches.',
    stageCode: '1-3',
    worldNumber: 1,
    stageNumber: 3,
    x: 0.59,
    y: 0.21,
    theme: 'physical',
    branch: 'world1',
    branchStep: 3,
    parent: 'world1Stage2',
    isBoss: false,
  },
  {
    id: 'world1Stage4',
    name: 'Canopy Sentinel Trial',
    description: 'Trial gates guard the approach to the sky castellum.',
    stageCode: '1-4',
    worldNumber: 1,
    stageNumber: 4,
    x: 0.62,
    y: 0.12,
    theme: 'physical',
    order: '✿',
    branch: 'world1',
    branchStep: 4,
    parent: 'world1Stage3',
    isBoss: false,
  },
  {
    id: 'world1Stage5',
    name: 'Verdant Castellum',
    description: 'Enter the sealed atrium to challenge the Psi Skywarden.',
    stageCode: '1-5',
    worldNumber: 1,
    stageNumber: 5,
    x: 0.62,
    y: 0.06,
    theme: 'boss',
    order: '◎',
    branch: 'world1',
    branchStep: 5,
    parent: 'world1Stage4',
    isBoss: true,
    bossName: 'Psi Skywarden',
    bossHp: 320,
    bossAttack: 130,
    bossDefense: 54,
  },

  // World 2: Glacier Peak (ice)
  {
    id: 'world2Stage1',
    name: 'Frostbite Pass',
    description: 'Sub-zero gusts chill the mountain trail.',
    stageCode: '2-1',
    worldNumber: 2,
    stageNumber: 1,
    x: 0.58,
    y: 0.42,
    theme: 'ice',
    branch: 'world2',
    branchStep: 1,
    parent: 'worldTree',
    isBoss: false,
  },
  {
    id: 'world2Stage2',
    name: 'Glacial Caverns',
    description: 'Slick ice shelves drop into bottomless rifts.',
    stageCode: '2-2',
    worldNumber: 2,
    stageNumber: 2,
    x: 0.66,
    y: 0.35,
    theme: 'ice',
    branch: 'world2',
    branchStep: 2,
    parent: 'world2Stage1',
    isBoss: false,
  },
  {
    id: 'world2Stage3',
    name: 'Rime Pinnacles',
    description: 'Jagged crystal spires pierce the winter fog.',
    stageCode: '2-3',
    worldNumber: 2,
    stageNumber: 3,
    x: 0.74,
    y: 0.27,
    theme: 'ice',
    branch: 'world2',
    branchStep: 3,
    parent: 'world2Stage2',
    isBoss: false,
  },
  {
    id: 'world2Stage4',
    name: 'Snowbound Ramparts',
    description: 'Frozen stone fortresses overlooking the white expanse.',
    stageCode: '2-4',
    worldNumber: 2,
    stageNumber: 4,
    x: 0.81,
    y: 0.20,
    theme: 'ice',
    branch: 'world2',
    branchStep: 4,
    parent: 'world2Stage3',
    isBoss: false,
  },
  {
    id: 'world2Stage5',
    name: 'Glacier Keep',
    description: 'A silent battlement awaits its cryoknight warden.',
    stageCode: '2-5',
    worldNumber: 2,
    stageNumber: 5,
    x: 0.88,
    y: 0.12,
    theme: 'boss',
    order: '◎',
    branch: 'world2',
    branchStep: 5,
    parent: 'world2Stage4',
    isBoss: true,
    bossName: 'Epsilon Cryowarden',
    bossHp: 420,
    bossAttack: 98,
    bossDefense: 60,
  },

  // World 3: Ashen Caldera (fire/lava)
  {
    id: 'world3Stage1',
    name: 'Cinder Slopes',
    description: 'Volcanic ash blankets the craggy ridges.',
    stageCode: '3-1',
    worldNumber: 3,
    stageNumber: 1,
    x: 0.60,
    y: 0.48,
    theme: 'fire',
    branch: 'world3',
    branchStep: 1,
    parent: 'worldTree',
    isBoss: false,
  },
  {
    id: 'world3Stage2',
    name: 'Magma Flues',
    description: 'Rivers of molten rock glow in deep trenches.',
    stageCode: '3-2',
    worldNumber: 3,
    stageNumber: 2,
    x: 0.69,
    y: 0.46,
    theme: 'lava',
    branch: 'world3',
    branchStep: 2,
    parent: 'world3Stage1',
    isBoss: false,
  },
  {
    id: 'world3Stage3',
    name: 'Obsidian Furnace',
    description: 'Extreme heat radiates from underground vents.',
    stageCode: '3-3',
    worldNumber: 3,
    stageNumber: 3,
    x: 0.78,
    y: 0.44,
    theme: 'fire',
    branch: 'world3',
    branchStep: 3,
    parent: 'world3Stage2',
    isBoss: false,
  },
  {
    id: 'world3Stage4',
    name: 'Brimstone Gates',
    description: 'Searing gates seal the caldera core.',
    stageCode: '3-4',
    worldNumber: 3,
    stageNumber: 4,
    x: 0.86,
    y: 0.42,
    theme: 'lava',
    branch: 'world3',
    branchStep: 4,
    parent: 'world3Stage3',
    isBoss: false,
  },
  {
    id: 'world3Stage5',
    name: 'Ashen Reliquary',
    description: 'The magma throne room and crucible of fire.',
    stageCode: '3-5',
    worldNumber: 3,
    stageNumber: 5,
    x: 0.94,
    y: 0.40,
    theme: 'boss',
    order: '◎',
    branch: 'world3',
    branchStep: 5,
    parent: 'world3Stage4',
    isBoss: true,
    bossName: 'Ignis Archon',
    bossHp: 480,
    bossAttack: 140,
    bossDefense: 62,
  },

  // World 4: Tidal Trench (water)
  {
    id: 'world4Stage1',
    name: 'Abyssal Engineworks',
    description: 'Ancient hydraulic pumps churn beneath the surface.',
    stageCode: '4-1',
    worldNumber: 4,
    stageNumber: 1,
    x: 0.5636,
    y: 0.5636,
    theme: 'water',
    order: '⚙',
    branch: 'world4',
    branchStep: 1,
    parent: 'worldTree',
    isBoss: false,
  },
  {
    id: 'world4Stage2',
    name: 'Tidal Wells',
    description: 'Submerged shafts echo with rising floodwaters.',
    stageCode: '4-2',
    worldNumber: 4,
    stageNumber: 2,
    x: 0.6272,
    y: 0.6272,
    theme: 'water',
    order: 'X',
    branch: 'world4',
    branchStep: 2,
    parent: 'world4Stage1',
    isBoss: false,
  },
  {
    id: 'world4Stage3',
    name: 'Twilight Trench',
    description: 'Sunlight fades in the ocean abyss.',
    stageCode: '4-3',
    worldNumber: 4,
    stageNumber: 3,
    x: 0.6908,
    y: 0.6908,
    theme: 'water',
    order: 'XI',
    branch: 'world4',
    branchStep: 3,
    parent: 'world4Stage2',
    isBoss: false,
  },
  {
    id: 'world4Stage4',
    name: 'Abyssal Crown',
    description: 'Coral ruins surrounding the deep leviathan lock.',
    stageCode: '4-4',
    worldNumber: 4,
    stageNumber: 4,
    x: 0.7544,
    y: 0.7544,
    theme: 'water',
    order: 'XII',
    branch: 'world4',
    branchStep: 4,
    parent: 'world4Stage3',
    isBoss: false,
  },
  {
    id: 'world4Stage5',
    name: 'Tidal Reliquary',
    description: 'Pressure doors seal the leviathan dock.',
    stageCode: '4-5',
    worldNumber: 4,
    stageNumber: 5,
    x: 0.8811,
    y: 0.8811,
    theme: 'boss',
    order: '◎',
    branch: 'world4',
    branchStep: 5,
    parent: 'world4Stage4',
    isBoss: true,
    bossName: 'Omega Tide Leviathan',
    bossHp: 510,
    bossAttack: 105,
    bossDefense: 65,
  },

  // World 5: Solar Dunes (light/stone)
  {
    id: 'world5Stage1',
    name: 'Inspire Dunes',
    description: 'Shifting sands bury forgotten ruins.',
    stageCode: '5-1',
    worldNumber: 5,
    stageNumber: 1,
    x: 0.50,
    y: 0.59,
    theme: 'stone',
    order: 'IX',
    branch: 'world5',
    branchStep: 1,
    parent: 'worldTree',
    isBoss: false,
  },
  {
    id: 'world5Stage2',
    name: 'Mirage Bazaar',
    description: 'Solar heat glimmers above deserted archways.',
    stageCode: '5-2',
    worldNumber: 5,
    stageNumber: 2,
    x: 0.50,
    y: 0.68,
    theme: 'stone',
    branch: 'world5',
    branchStep: 2,
    parent: 'world5Stage1',
    isBoss: false,
  },
  {
    id: 'world5Stage3',
    name: 'Sirocco Causeway',
    description: 'Sandstorms scour the stone causeway.',
    stageCode: '5-3',
    worldNumber: 5,
    stageNumber: 3,
    x: 0.50,
    y: 0.77,
    theme: 'stone',
    branch: 'world5',
    branchStep: 3,
    parent: 'world5Stage2',
    isBoss: false,
  },
  {
    id: 'world5Stage4',
    name: 'Auric Apex Citadel',
    description: 'Golden pyramid gates seal the solar reliquary.',
    stageCode: '5-4',
    worldNumber: 5,
    stageNumber: 4,
    x: 0.50,
    y: 0.86,
    theme: 'stone',
    order: '♛',
    branch: 'world5',
    branchStep: 4,
    parent: 'world5Stage3',
    isBoss: false,
  },
  {
    id: 'world5Stage5',
    name: 'Phi Sun Reliquary',
    description: 'Descend beneath the dunes to face the luminary guarding the pyramid core.',
    stageCode: '5-5',
    worldNumber: 5,
    stageNumber: 5,
    x: 0.50,
    y: 0.98,
    theme: 'boss',
    order: '◎',
    branch: 'world5',
    branchStep: 5,
    parent: 'world5Stage4',
    isBoss: true,
    bossName: 'Phi Sun Hierophant',
    bossHp: 520,
    bossAttack: 112,
    bossDefense: 68,
  },

  // World 6: Obsidian Abyss (void/dark)
  {
    id: 'world6Stage1',
    name: 'Umbral Reliquary',
    description: 'Basalt pillars rise from perpetual gloom.',
    stageCode: '6-1',
    worldNumber: 6,
    stageNumber: 1,
    x: 0.4364,
    y: 0.5636,
    theme: 'metal',
    order: 'XIII',
    branch: 'world6',
    branchStep: 1,
    parent: 'worldTree',
    isBoss: false,
  },
  {
    id: 'world6Stage2',
    name: 'Gloomfall Colonnade',
    description: 'Darkness deepens as the stone arches crumble.',
    stageCode: '6-2',
    worldNumber: 6,
    stageNumber: 2,
    x: 0.3728,
    y: 0.6272,
    theme: 'metal',
    order: 'XIV',
    branch: 'world6',
    branchStep: 2,
    parent: 'world6Stage1',
    isBoss: false,
  },
  {
    id: 'world6Stage3',
    name: 'Obsidian Warrens',
    description: 'Labyrinthine tunnels of solid volcanic glass.',
    stageCode: '6-3',
    worldNumber: 6,
    stageNumber: 3,
    x: 0.3092,
    y: 0.6908,
    theme: 'metal',
    order: 'XV',
    branch: 'world6',
    branchStep: 3,
    parent: 'world6Stage2',
    isBoss: false,
  },
  {
    id: 'world6Stage4',
    name: 'Midnight Throne',
    description: 'An ancient basalt court under shadow.',
    stageCode: '6-4',
    worldNumber: 6,
    stageNumber: 4,
    x: 0.2456,
    y: 0.7544,
    theme: 'metal',
    order: 'XVI',
    branch: 'world6',
    branchStep: 4,
    parent: 'world6Stage3',
    isBoss: false,
  },
  {
    id: 'world6Stage5',
    name: 'Obsidian Amphitheater',
    description: 'Crystalline spires hum over the harmonic stage.',
    stageCode: '6-5',
    worldNumber: 6,
    stageNumber: 5,
    x: 0.1189,
    y: 0.8811,
    theme: 'boss',
    order: '◎',
    branch: 'world6',
    branchStep: 5,
    parent: 'world6Stage4',
    isBoss: true,
    bossName: 'Theta Harmonic',
    bossHp: 560,
    bossAttack: 136,
    bossDefense: 72,
  },

  // World 7: Chrono Spire (clockwork/time)
  {
    id: 'world7Stage1',
    name: 'Chronometric Sanctum',
    description: 'Giant pendulum mechanisms measure the passage of aeons.',
    stageCode: '7-1',
    worldNumber: 7,
    stageNumber: 1,
    x: 0.41,
    y: 0.50,
    theme: 'metal',
    order: 'XXI',
    branch: 'world7',
    branchStep: 1,
    parent: 'worldTree',
    isBoss: false,
  },
  {
    id: 'world7Stage2',
    name: 'Pendulum Engine',
    description: 'Clockwork pistons swing across perilous gaps.',
    stageCode: '7-2',
    worldNumber: 7,
    stageNumber: 2,
    x: 0.32,
    y: 0.50,
    theme: 'metal',
    order: 'XXII',
    branch: 'world7',
    branchStep: 2,
    parent: 'world7Stage1',
    isBoss: false,
  },
  {
    id: 'world7Stage3',
    name: 'Gear Spire Ascent',
    description: 'Interlocking brass gears turn endlessly in the vertical shaft.',
    stageCode: '7-3',
    worldNumber: 7,
    stageNumber: 3,
    x: 0.23,
    y: 0.50,
    theme: 'metal',
    order: 'XXIII',
    branch: 'world7',
    branchStep: 3,
    parent: 'world7Stage2',
    isBoss: false,
  },
  {
    id: 'world7Stage4',
    name: 'Clocktower Crown',
    description: 'The pinnacle overlooking temporal currents.',
    stageCode: '7-4',
    worldNumber: 7,
    stageNumber: 4,
    x: 0.14,
    y: 0.50,
    theme: 'metal',
    order: 'XXIV',
    branch: 'world7',
    branchStep: 4,
    parent: 'world7Stage3',
    isBoss: false,
  },
  {
    id: 'world7Stage5',
    name: 'Chrono Apex',
    description: 'Clockwork ticks echo across the silent temporal oculus.',
    stageCode: '7-5',
    worldNumber: 7,
    stageNumber: 5,
    x: 0.06,
    y: 0.40,
    theme: 'boss',
    order: '◎',
    branch: 'world7',
    branchStep: 5,
    parent: 'world7Stage4',
    isBoss: true,
    bossName: 'Chronos Ward',
    bossHp: 590,
    bossAttack: 145,
    bossDefense: 74,
  },

  // World 8: Parallax Void (liminal/void)
  {
    id: 'world8Stage1',
    name: 'Space Between Time',
    description: 'Floating fragments drift in the null gradient.',
    stageCode: '8-1',
    worldNumber: 8,
    stageNumber: 1,
    x: 0.44,
    y: 0.44,
    theme: 'physical',
    order: 'XVII',
    branch: 'world8',
    branchStep: 1,
    parent: 'worldTree',
    isBoss: false,
  },
  {
    id: 'world8Stage2',
    name: 'Spiral of Lost Stars',
    description: 'Constellations distort in the gravitational well.',
    stageCode: '8-2',
    worldNumber: 8,
    stageNumber: 2,
    x: 0.37,
    y: 0.37,
    theme: 'physical',
    order: 'XVIII',
    branch: 'world8',
    branchStep: 2,
    parent: 'world8Stage1',
    isBoss: false,
  },
  {
    id: 'world8Stage3',
    name: 'Liminal Guile',
    description: 'Fractured reality shimmers in the void rifts.',
    stageCode: '8-3',
    worldNumber: 8,
    stageNumber: 3,
    x: 0.31,
    y: 0.31,
    theme: 'physical',
    order: 'XIX',
    branch: 'world8',
    branchStep: 3,
    parent: 'world8Stage2',
    isBoss: false,
  },
  {
    id: 'world8Stage4',
    name: 'Parallax Model',
    description: 'Dimensional membranes warp at the threshold of the nexus.',
    stageCode: '8-4',
    worldNumber: 8,
    stageNumber: 4,
    x: 0.25,
    y: 0.25,
    theme: 'physical',
    order: 'XX',
    branch: 'world8',
    branchStep: 4,
    parent: 'world8Stage3',
    isBoss: false,
  },
  {
    id: 'world8Stage5',
    name: 'Parallax Nexus',
    description: 'A void chamber and gravitational center of all worlds.',
    stageCode: '8-5',
    worldNumber: 8,
    stageNumber: 5,
    x: 0.1189,
    y: 0.1189,
    theme: 'boss',
    order: '◎',
    branch: 'world8',
    branchStep: 5,
    parent: 'world8Stage4',
    isBoss: true,
    bossName: 'The Void Herald',
    bossHp: 650,
    bossAttack: 160,
    bossDefense: 80,
  },
];

/** Links between nodes (hub -> branches and stage -> next stage). */
export function computeWorldMapLinks(): WorldMapLinkDef[] {
  const links: WorldMapLinkDef[] = [];
  const linkSet = new Set<string>();

  for (const node of WORLD_MAP_NODES) {
    if (node.parent) {
      const key = `${node.parent}->${node.id}`;
      if (!linkSet.has(key)) {
        linkSet.add(key);
        links.push({ fromId: node.parent, toId: node.id });
      }
    }
  }
  return links;
}

/** Determines if a world map node is unlocked given completed stage codes/IDs. */
export function isWorldMapNodeUnlocked(
  node: WorldMapNodeDef,
  completedIds: ReadonlySet<string>,
): boolean {
  if (node.id === 'worldTree') return true;
  if (node.standalone || node.optional) return true;
  if (node.parent === 'worldTree') return true; // Branch step 1 is always unlocked
  if (node.parent && completedIds.has(node.parent)) return true;
  if (node.requiresStages && node.requiresStages.every(id => completedIds.has(id))) return true;
  return false;
}

/** Look up a node by its ID or stage code. */
export function findWorldMapNode(idOrCode: string): WorldMapNodeDef | undefined {
  if (idOrCode === 'worldTree' || idOrCode === 'HUB') return WORLD_TREE_HUB_NODE;
  return WORLD_MAP_NODES.find(n => n.id === idOrCode || n.stageCode === idOrCode);
}
