/**
 * gameCommandProcessor.ts — Player input command dispatch for the game screen.
 *
 * Translates raw GameCommand inputs into world state mutations and returns
 * a result record used by the game loop to drive further game-state changes
 * (pause menu, death handling, etc.).  All side-effectful state mutations are
 * applied directly to `world`; the caller handles UI callbacks using the
 * returned flags.
 */

import { collectCommands, InputState } from '../input/handler';
import { CommandKind } from '../input/commands';
import {
  arbitrateExclusivePlayerActions,
  getActiveExclusivePlayerAction,
} from '../input/playerActionArbitration';
import { WorldState } from '../sim/world';
import { fireGrapple } from '../sim/clusters/grapple';
import { GrappleInputMode } from '../sim/worldGrappleState';
import { getWallJumpCandidate } from '../sim/clusters/playerWallJump';
import { screenToWorld } from './gameRoom';
import {
  tryStartPlayerWeaponAttack,
  releasePlayerWeaponAttack,
  getEquippedWeaponDef,
} from '../sim/weapons/playerWeaponState';
import { getDoubleJumpToGrappleEnabled } from '../ui/renderSettings';
import { SkillTombRenderer } from '../render/skillTombRenderer';
import { SkillTombEffectRenderer } from '../render/skillTombEffectRenderer';
import type { PlayerProgress } from '../progression/playerProgress';
import type { CombatTextSystem } from '../render/hud/combatText';
import { unlockActiveWeave, unlockDustType } from '../progression/unlocks';
import { getWeaveDefinition } from '../sim/weaves/weaveDefinition';
import { expandLegacyWeaveId } from '../progression/weaveMigration';
import type { RoomDef } from '../levels/roomDef';
import { BLOCK_SIZE_MEDIUM } from '../levels/roomDef';
import type { RngState } from '../sim/rng';
import { isEquippableParticleKind } from '../sim/particles/kinds';
import { stringToParticleKind } from '../editor/roomJsonSchema';
import { grantOverhealthMotes } from '../sim/playerMoteLife';
import { grantTemporaryHitPoints } from '../sim/playerHealth';
import { getDustDefinition } from '../sim/weaves/dustDefinition';
import type { DustSelectionWheelController } from './gameDustSelectionState';

/** Radius within which the player can collect a dust swarm by pressing F. */
const DUST_SWARM_COLLECT_RADIUS_WORLD = BLOCK_SIZE_MEDIUM * 2;

/**
 * Commands generated by the grapple-fire / primary-weave / secondary-weave
 * physical inputs that must never leak through while the dust wheel is open —
 * the entire press/hold/release gesture is captured for wheel selection
 * instead. GrappleFire is handled specially (it drives selection); every
 * other kind here is simply dropped for the frame.
 */
export function isDustWheelSuppressedCommandKind(kind: CommandKind): boolean {
  switch (kind) {
    case CommandKind.GrappleRelease:
    case CommandKind.GrappleZip:
    case CommandKind.WeaveActivatePrimary:
    case CommandKind.WeaveHoldPrimary:
    case CommandKind.WeaveEndPrimary:
    case CommandKind.WeaveActivateSecondary:
    case CommandKind.WeaveHoldSecondary:
    case CommandKind.WeaveEndSecondary:
    case CommandKind.ShieldWeaveHold:
    case CommandKind.ShieldWeaveEnd:
    case CommandKind.Attack:
    case CommandKind.BlockStart:
    case CommandKind.BlockUpdate:
    case CommandKind.BlockEnd:
      return true;
    default:
      return false;
  }
}

function canJumpInputBecomeGrapple(ctx: GameCommandContext): boolean {
  if (ctx.dustWheel.shouldCaptureGrappleWeaveInput()) return false;
  if (!getDoubleJumpToGrappleEnabled()) return false;
  if (ctx.world.isPlayerInWaterFlag === 1) return false;

  const player = ctx.world.clusters[0];
  if (player === undefined || player.isAliveFlag === 0) return false;
  if (ctx.world.isGrappleActiveFlag === 1) return false;
  if (player.isGroundedFlag === 1 || player.coyoteTimeTicks > 0) return false;
  if (player.wallJumpForceTimeTicks > 0) return false;

  const wallJumpCandidate = getWallJumpCandidate(player, ctx.world);
  return !wallJumpCandidate.canJumpFromLeft && !wallJumpCandidate.canJumpFromRight;
}

function fireGrappleAtScreenPoint(ctx: GameCommandContext, aimXPx: number, aimYPx: number): void {
  const aim = screenToWorld(
    aimXPx,
    aimYPx,
    ctx.offsetXPx,
    ctx.offsetYPx,
    ctx.zoom,
    ctx.canvas.width,
    ctx.canvas.height,
    ctx.virtualWidthPx,
    ctx.virtualHeightPx,
  );
  fireGrapple(ctx.world, aim.xWorld, aim.yWorld);
}

/** Context passed to {@link processPlayerCommands} each frame. */
export interface GameCommandContext {
  inputState: InputState;
  world: WorldState;
  canvas: HTMLCanvasElement;
  offsetXPx: number;
  offsetYPx: number;
  zoom: number;
  virtualWidthPx: number;
  virtualHeightPx: number;
  skillTombRenderer: SkillTombRenderer;
  skillTombEffectRenderer: SkillTombEffectRenderer;
  progress: PlayerProgress | undefined;
  consumedSkillTombKeySet: Set<string>;
  combatText: CombatTextSystem;
  currentRoomId: string;
  openMapOnly: () => void;
  /** Opens the inventory screen (equipment + carried items). */
  openInventory: () => void;
  /** The active room definition (used for dust swarm pickups). */
  currentRoom: RoomDef;
  /** Keys in the format `${roomId}:dustswarm:${index}` for collected dust swarms. */
  collectedDustSwarmKeySet: Set<string>;
  /** Room-level RNG for particle spawning. */
  levelRng: RngState;
  /** Wall-clock timestamp for the current frame (ms); used for UI animations only. */
  nowMs: number;
  /** Index (0-based) into `currentRoom.lambdaAnchors[]` for the linked anchor, or -1 if none. */
  linkedAnchorIndex: number;
  /** Room ID of the room where the linked anchor lives, or '' if none. */
  linkedAnchorRoomId: string;
  /** Called to link (or re-link) to anchor `index` in room `roomId`. */
  setLambdaAnchorLink: (index: number, roomId: string) => void;
  /** Called to clear the lambda anchor link. */
  clearLambdaAnchorLink: () => void;
  /** Called to trigger a teleport flash effect. `alpha` starts at 1.0. */
  lambdaTeleportFlash: () => void;
  /** Dust selection wheel controller — gates/captures grapple+weave input while open. */
  dustWheel: DustSelectionWheelController;
}

/** Output of {@link processPlayerCommands} consumed by the game loop. */
export interface GameCommandResult {
  /** Horizontal movement input: -1 (left), 0 (none), 1 (right). */
  moveDx: number;
  /** True when a jump command was received this frame. */
  jumpTriggered: boolean;
  /** True when the player requested to open the pause/return-to-map menu. */
  openPause: boolean;
  /** True when an interact command landed near a save tomb. */
  interactTriggered: boolean;
  /** True when the interact command fired (caller should start the interact pulse timer). */
  interactInputPulseTrigger: boolean;
  /** True when a grapple fire command was accepted for the player this frame. */
  grappleFireTriggered: boolean;
}

/**
 * Processes all buffered player input commands for the current frame.
 *
 * Mutates `ctx.world` for weave/grapple commands; all other outcomes are
 * returned as flags for the caller to act on.
 */
export function processPlayerCommands(ctx: GameCommandContext): GameCommandResult {
  const {
    inputState, world, canvas,
    offsetXPx, offsetYPx, zoom,
    virtualWidthPx, virtualHeightPx,
    skillTombRenderer, skillTombEffectRenderer,
    progress, consumedSkillTombKeySet, combatText,
    currentRoomId, openMapOnly, openInventory,
    currentRoom, collectedDustSwarmKeySet, nowMs,
    linkedAnchorIndex, linkedAnchorRoomId,
    setLambdaAnchorLink, clearLambdaAnchorLink, lambdaTeleportFlash,
  } = ctx;

  const commands = collectCommands(inputState);
  const grappleRequested = commands.some(command =>
    command.kind === CommandKind.GrappleFire
    || (command.kind === CommandKind.Jump && canJumpInputBecomeGrapple(ctx)));
  const shieldWeaveRequested = commands.some(command => command.kind === CommandKind.ShieldWeaveHold);
  const exclusiveAction = arbitrateExclusivePlayerActions(
    getActiveExclusivePlayerAction(
      world.isGrappleActiveFlag === 1,
      world.shieldWeave.isActive,
    ),
    { grapple: grappleRequested, shieldWeave: shieldWeaveRequested },
  );
  let openPause = false;
  let moveDx = 0;
  let jumpTriggered = false;
  let interactTriggered = false;
  let interactInputPulseTrigger = false;
  let grappleFireTriggered = false;

  // ── Dust selection wheel: continuous highlight + input capture ───────────
  // The latch must be advanced every frame (even when the wheel is fully
  // closed) so it clears as soon as the physical grapple-fire / secondary
  // button that made the last selection/cancellation returns to neutral.
  ctx.dustWheel.updateInputCaptureLatch(
    inputState.isGrappleHeldFlag === 1,
    inputState.isRightMouseDownFlag === 1,
  );
  if (ctx.dustWheel.isOpen()) {
    const wheelPlayer = world.clusters[0];
    if (wheelPlayer !== undefined && wheelPlayer.isAliveFlag === 1) {
      const hoverAim = screenToWorld(
        inputState.mouseXPx, inputState.mouseYPx,
        offsetXPx, offsetYPx, zoom, canvas.width, canvas.height, virtualWidthPx, virtualHeightPx,
      );
      ctx.dustWheel.updateHighlightFromAim(
        wheelPlayer.positionXWorld, wheelPlayer.positionYWorld,
        hoverAim.xWorld, hoverAim.yWorld,
      );
    }
  }

  for (let ci = 0; ci < commands.length; ci++) {
    const cmd = commands[ci];

    if (ctx.dustWheel.isOpen() && cmd.kind === CommandKind.GrappleFire) {
      const player = world.clusters[0];
      if (player !== undefined && player.isAliveFlag === 1) {
        const aim = screenToWorld(cmd.aimXPx, cmd.aimYPx, offsetXPx, offsetYPx, zoom, canvas.width, canvas.height, virtualWidthPx, virtualHeightPx);
        ctx.dustWheel.selectAtAim(world, progress, aim.xWorld, aim.yWorld, player.positionXWorld, player.positionYWorld, nowMs);
      }
      continue; // the grapple must never actually fire while the wheel is open
    }

    if (ctx.dustWheel.shouldCaptureGrappleWeaveInput()) {
      // Covers both "still open" (any suppressed kind including a second
      // GrappleFire once the dead zone consumed the first) and the brief
      // post-close latch window while the selecting button is still held.
      if (cmd.kind === CommandKind.GrappleFire || isDustWheelSuppressedCommandKind(cmd.kind)) continue;
    }

    if (cmd.kind === CommandKind.ReturnToMap) {
      openPause = true;
    } else if (cmd.kind === CommandKind.MovePlayer) {
      moveDx = cmd.dx;
    } else if (cmd.kind === CommandKind.Jump) {
      if (canJumpInputBecomeGrapple(ctx)) {
        if (exclusiveAction.allowGrapple) {
          fireGrappleAtScreenPoint(ctx, inputState.mouseXPx, inputState.mouseYPx);
          grappleFireTriggered = true;
        }
      } else {
        jumpTriggered = true;
      }
    } else if (cmd.kind === CommandKind.Attack) {
      // Legacy attack command — no longer used for player (enemies still use it internally)
      // Kept for backward compatibility; ignored for player
    } else if (cmd.kind === CommandKind.BlockStart || cmd.kind === CommandKind.BlockUpdate) {
      // Legacy block command — no longer used for player
    } else if (cmd.kind === CommandKind.BlockEnd) {
      // Legacy block end — no longer used for player
    } else if (cmd.kind === CommandKind.WeaveActivatePrimary) {
      const player = world.clusters[0];
      if (player !== undefined && player.isAliveFlag === 1) {
        const aim = screenToWorld(cmd.aimXPx, cmd.aimYPx, offsetXPx, offsetYPx, zoom, canvas.width, canvas.height, virtualWidthPx, virtualHeightPx);
        // Check if tapping/clicking on a skill tomb (save point)
        const tombIndex = skillTombRenderer.getNearbyTombIndex(aim.xWorld, aim.yWorld);
        if (tombIndex >= 0) {
          // Player is also near the tomb — open the save menu
          const playerNearby = skillTombRenderer.getNearbyTombIndex(player.positionXWorld, player.positionYWorld);
          if (playerNearby >= 0) {
            interactTriggered = true;
          }
        } else {
          // Normal weave attack
          let dirX = aim.xWorld - player.positionXWorld;
          let dirY = aim.yWorld - player.positionYWorld;
          const len = Math.sqrt(dirX * dirX + dirY * dirY);
          if (len < 1.0) { dirX = 1.0; dirY = 0.0; } else { dirX /= len; dirY /= len; }
          world.playerWeaveAimDirXWorld = dirX;
          world.playerWeaveAimDirYWorld = dirY;
          world.playerPrimaryWeaveTriggeredFlag = 1;
        }
      }
    } else if (cmd.kind === CommandKind.WeaveHoldPrimary) {
      const player = world.clusters[0];
      if (player !== undefined && player.isAliveFlag === 1) {
        const aim = screenToWorld(cmd.aimXPx, cmd.aimYPx, offsetXPx, offsetYPx, zoom, canvas.width, canvas.height, virtualWidthPx, virtualHeightPx);
        let dirX = aim.xWorld - player.positionXWorld;
        let dirY = aim.yWorld - player.positionYWorld;
        const len = Math.sqrt(dirX * dirX + dirY * dirY);
        if (len < 1.0) { dirX = world.playerWeaveAimDirXWorld; dirY = world.playerWeaveAimDirYWorld; }
        else { dirX /= len; dirY /= len; }
        world.playerWeaveAimDirXWorld = dirX;
        world.playerWeaveAimDirYWorld = dirY;
        // For sustained weaves, trigger on first hold frame
        if (world.isPlayerPrimaryWeaveActiveFlag === 0) {
          world.playerPrimaryWeaveTriggeredFlag = 1;
        }
      }
    } else if (cmd.kind === CommandKind.WeaveEndPrimary) {
      world.playerPrimaryWeaveEndFlag = 1;
    } else if (cmd.kind === CommandKind.GrappleZip) {
      // Right mouse pressed — zip toward anchor if grapple is attached.
      // If no grapple is active, the subsequent Shield Weave command handles it.
      if (world.isGrappleActiveFlag === 1) {
        if (world.isGrappleZipActiveFlag === 0) {
          world.isGrappleZipTriggeredFlag = 1;
        }
      }
    } else if (cmd.kind === CommandKind.ShieldWeaveHold) {
      const player = world.clusters[0];
      // A weapon's secondary (the right mouse button) raises the shield only
      // when the equipped weapon grants one — the weave swords do, everything
      // else ignores the button. The gamepad's own trigger is unconditional, so
      // this gate applies only when the weapon secondary is the sole source.
      const weaponGrantsShield = getEquippedWeaponDef(world.playerWeapon)?.secondaryShieldWeave === true;
      const allowedBySource = inputState.isShieldWeaveHeldFlag === 1 || weaponGrantsShield;
      if (!allowedBySource || !exclusiveAction.allowShieldWeave
        || player === undefined || player.isAliveFlag === 0) {
        world.shieldWeave.isHeldRequested = false;
        world.shieldWeave.isActive = false;
        world.shieldWeaveDustKindOverride = -1;
      } else {
        const aim = screenToWorld(cmd.aimXPx, cmd.aimYPx, offsetXPx, offsetYPx, zoom, canvas.width, canvas.height, virtualWidthPx, virtualHeightPx);
        const dx = aim.xWorld - player.positionXWorld;
        const dy = aim.yWorld - player.positionYWorld;
        const length = Math.hypot(dx, dy);
        if (length >= 0.001) {
          world.playerWeaveAimDirXWorld = dx / length;
          world.playerWeaveAimDirYWorld = dy / length;
        }
        world.shieldWeave.isHeldRequested = true;
        // Weave the arc from the sword's own dust while it is the source.
        const weaveDust = getEquippedWeaponDef(world.playerWeapon)?.weaveDust;
        world.shieldWeaveDustKindOverride =
          inputState.isShieldWeaveHeldFlag === 0 && typeof weaveDust === 'number' ? weaveDust : -1;
      }
    } else if (cmd.kind === CommandKind.ShieldWeaveEnd) {
      world.shieldWeave.isHeldRequested = false;
      world.shieldWeave.isActive = false;
      world.shieldWeaveDustKindOverride = -1;
    } else if (cmd.kind === CommandKind.WeaveActivateSecondary) {
      // Skip secondary Weave while grapple is active (right-click = zip in that state).
      if (!world.isGrappleActiveFlag) {
        const player = world.clusters[0];
        if (player !== undefined && player.isAliveFlag === 1) {
          const aim = screenToWorld(cmd.aimXPx, cmd.aimYPx, offsetXPx, offsetYPx, zoom, canvas.width, canvas.height, virtualWidthPx, virtualHeightPx);
          let dirX = aim.xWorld - player.positionXWorld;
          let dirY = aim.yWorld - player.positionYWorld;
          const len = Math.sqrt(dirX * dirX + dirY * dirY);
          if (len < 1.0) { dirX = 1.0; dirY = 0.0; } else { dirX /= len; dirY /= len; }
          world.playerWeaveAimDirXWorld = dirX;
          world.playerWeaveAimDirYWorld = dirY;
          world.playerSecondaryWeaveTriggeredFlag = 1;
        }
      }
    } else if (cmd.kind === CommandKind.WeaveHoldSecondary) {
      // Suppress secondary Weave sustained hold while grapple is active (RMB = zip).
      if (!world.isGrappleActiveFlag) {
        const player = world.clusters[0];
        if (player !== undefined && player.isAliveFlag === 1) {
          const aim = screenToWorld(cmd.aimXPx, cmd.aimYPx, offsetXPx, offsetYPx, zoom, canvas.width, canvas.height, virtualWidthPx, virtualHeightPx);
          let dirX = aim.xWorld - player.positionXWorld;
          let dirY = aim.yWorld - player.positionYWorld;
          const len = Math.sqrt(dirX * dirX + dirY * dirY);
          if (len < 1.0) { dirX = world.playerWeaveAimDirXWorld; dirY = world.playerWeaveAimDirYWorld; }
          else { dirX /= len; dirY /= len; }
          world.playerWeaveAimDirXWorld = dirX;
          world.playerWeaveAimDirYWorld = dirY;
          if (world.isPlayerSecondaryWeaveActiveFlag === 0) {
            world.playerSecondaryWeaveTriggeredFlag = 1;
          }
        }
      }
    } else if (cmd.kind === CommandKind.WeaveEndSecondary) {
      if (!world.isGrappleActiveFlag) {
        world.playerSecondaryWeaveEndFlag = 1;
      }
    } else if (cmd.kind === CommandKind.GrappleFire) {
      const player = world.clusters[0];
      if (player !== undefined && player.isAliveFlag === 1) {
        if (world.grappleInputMode === GrappleInputMode.Toggle && world.isGrappleActiveFlag === 1) {
          // Toggle mode: a second left-click releases the grapple instead of
          // re-firing. This runs at render-frame command-processing time, not
          // inside the deterministic fixed tick, so queue the request rather
          // than releasing immediately — applyGrappleClusterConstraint()
          // consumes it at the correct point in the next fixed tick, once
          // that tick's swing physics has finished updating true velocity.
          world.isGrappleQuietReleaseRequestedFlag = 1;
        } else if (exclusiveAction.allowGrapple) {
          fireGrappleAtScreenPoint(ctx, cmd.aimXPx, cmd.aimYPx);
          grappleFireTriggered = true;
          // If RMB is held while firing, trigger an instant zip toward the new anchor.
          if (world.isGrappleActiveFlag === 1 && world.isGrappleZipActiveFlag === 0
              && ctx.inputState.isRightMouseDownFlag === 1) {
            world.isGrappleZipTriggeredFlag = 1;
          }
        }
      }
    } else if (cmd.kind === CommandKind.GrappleRelease) {
      // In Hold mode the grapple releases on mouse-up.
      // In Toggle mode releasing the mouse does nothing; the player clicks again to release.
      // Queued (not immediate) for the same reason as the Toggle-mode release
      // above: this command is processed once per rendered frame, decoupled
      // from the fixed simulation tick that owns the player's true velocity.
      if (world.grappleInputMode === GrappleInputMode.Hold) {
        world.isGrappleQuietReleaseRequestedFlag = 1;
      }
    } else if (cmd.kind === CommandKind.ToggleFullscreen) {
      if (!document.fullscreenElement) {
        // Enter fullscreen on key press (requires user gesture; keydown path satisfies this).
        void document.documentElement.requestFullscreen().catch(() => {});
      }
    } else if (cmd.kind === CommandKind.OpenMap) {
      openMapOnly();
    } else if (cmd.kind === CommandKind.OpenInventory) {
      openInventory();
    } else if (cmd.kind === CommandKind.Interact) {
      interactInputPulseTrigger = true;
      const playerForInteract = world.clusters[0];
      if (playerForInteract !== undefined && playerForInteract.isAliveFlag === 1) {
        // Check if player is near a save tomb (opens the save menu)
        const nearbyIndex = skillTombRenderer.getNearbyTombIndex(
          playerForInteract.positionXWorld, playerForInteract.positionYWorld,
        );
        if (nearbyIndex >= 0) {
          interactTriggered = true;
        }
        // Check if player is near a skill tomb (unlocks a dust weave).
        // Only show the weave-obtained label — do NOT open the motes menu.
        const nearbySkillTombIndex = skillTombEffectRenderer.getNearbyTombIndex(
          playerForInteract.positionXWorld, playerForInteract.positionYWorld,
        );
        if (nearbySkillTombIndex >= 0 && progress) {
          const tombPositionKey = skillTombEffectRenderer.getTombPositionKey(nearbySkillTombIndex);
          const consumedKey = `${currentRoomId}:${tombPositionKey}`;
          if (!consumedSkillTombKeySet.has(consumedKey)) {
            const weaveId = skillTombEffectRenderer.getTombWeaveId(nearbySkillTombIndex);
            // Expand legacy combo ids (e.g. the old `shield_sword` book) into
            // every independent weave they imply so old room data still
            // grants both Sword and Shield — never silently drops an
            // ability. Unknown ids fall back to granting themselves as-is so
            // malformed authored data never throws.
            const grantedWeaveIds = expandLegacyWeaveId(weaveId);
            const idsToGrant = grantedWeaveIds.length > 0 ? grantedWeaveIds : [weaveId];
            for (const id of idsToGrant) unlockActiveWeave(progress, id);
            consumedSkillTombKeySet.add(consumedKey);
            if (progress.collectedSkillTombKeys.indexOf(consumedKey) === -1) {
              progress.collectedSkillTombKeys.push(consumedKey);
            }
            skillTombEffectRenderer.removeTomb(nearbySkillTombIndex);
            const weaveName = getWeaveDefinition(weaveId)?.displayName ?? 'Unknown Weave';
            combatText.spawnLabel(
              playerForInteract.positionXWorld,
              playerForInteract.positionYWorld - 10,
              `${weaveName} Obtained`,
              nowMs,
            );
          }
          // Do NOT set interactTriggered — picking up a weave should not open the motes menu.
        }

        // ── Dust swarm collection ──────────────────────────────────────────────
        // Player presses F near a dust swarm to collect it, receiving dust particles.
        const roomDustSwarms = currentRoom.dustSwarms ?? [];
        for (let i = 0; i < roomDustSwarms.length; i++) {
          const swarmKey = `${currentRoomId}:dustswarm:${i}`;
          if (collectedDustSwarmKeySet.has(swarmKey)) continue;
          const sw = roomDustSwarms[i];
          const swCx = (sw.xBlock + 0.5) * BLOCK_SIZE_MEDIUM;
          const swCy = (sw.yBlock + 0.5) * BLOCK_SIZE_MEDIUM;
          const sdx = playerForInteract.positionXWorld - swCx;
          const sdy = playerForInteract.positionYWorld - swCy;
          if (sdx * sdx + sdy * sdy <= DUST_SWARM_COLLECT_RADIUS_WORLD * DUST_SWARM_COLLECT_RADIUS_WORLD) {
            const rawKind = stringToParticleKind(sw.dustKind);
            // Legacy rooms may contain kinds that remain valid internally but
            // are no longer player collectibles. Leave authored data untouched
            // while preventing those swarms from entering progression/loadouts.
            if (rawKind === null || !isEquippableParticleKind(rawKind)) continue;
            const dustKind = rawKind;
            collectedDustSwarmKeySet.add(swarmKey);
            // Permanently unlock this dust type in the player's progression.
            if (progress) {
              unlockDustType(progress, dustKind);
              // Persist swarm collection key so swarms don't reappear after save/load.
              if (!progress.collectedDustSwarmKeys.includes(swarmKey)) {
                progress.collectedDustSwarmKeys.push(swarmKey);
              }
            }
            // Grant the swarm's dust as overhealth directly onto current
            // health — this only runs on first collection (gated by
            // collectedDustSwarmKeySet above, which is seeded from
            // progress.collectedDustSwarmKeys on room load, so reloading a
            // save with an already-collected swarm never re-grants). Must
            // not spawn a second player-owned legacy particle cloud.
            grantOverhealthMotes(playerForInteract, sw.dustCount);
            // Motes and hit points are separate pools (`sim/playerHealth.ts`).
            grantTemporaryHitPoints(playerForInteract, sw.dustCount);
            const kindName = getDustDefinition(dustKind).displayName;
            combatText.spawnLabel(
              playerForInteract.positionXWorld,
              playerForInteract.positionYWorld - 10,
              `+${sw.dustCount} ${kindName}`,
              nowMs,
            );
          }
        }
        // ── Lambda Anchor interaction ──────────────────────────────────────────
        // First press F near anchor → link. Second press F while already linked
        // in this room → teleport back to the anchor's position.
        const LAMBDA_INTERACT_RADIUS_WORLD = BLOCK_SIZE_MEDIUM * 2;
        const roomAnchors = currentRoom.lambdaAnchors ?? [];
        for (let i = 0; i < roomAnchors.length; i++) {
          const anchor = roomAnchors[i];
          const anchorCX = (anchor.xBlock + 0.5) * BLOCK_SIZE_MEDIUM;
          const anchorCY = (anchor.yBlock + 0.5) * BLOCK_SIZE_MEDIUM;
          const adx = playerForInteract.positionXWorld - anchorCX;
          const ady = playerForInteract.positionYWorld - anchorCY;
          const distSq = adx * adx + ady * ady;
          if (distSq > LAMBDA_INTERACT_RADIUS_WORLD * LAMBDA_INTERACT_RADIUS_WORLD) continue;

          if (linkedAnchorIndex === i && linkedAnchorRoomId === currentRoomId) {
            // Already linked to this anchor — teleport back to it.
            const player = world.clusters.find(c => c.isPlayerFlag === 1);
            if (player) {
              player.positionXWorld = anchorCX;
              player.positionYWorld = anchorCY - player.halfHeightWorld;
              player.velocityXWorld = 0;
              player.velocityYWorld = 0;
              lambdaTeleportFlash();
              clearLambdaAnchorLink();
            }
          } else {
            // Not yet linked — link to this anchor.
            setLambdaAnchorLink(i, currentRoomId);
            combatText.spawnLabel(
              playerForInteract.positionXWorld,
              playerForInteract.positionYWorld - 10,
              'Anchor Linked',
              nowMs,
            );
          }
          break; // Only interact with the nearest anchor (first match).
        }
      }
    }
  }

  // ── STICK-RPG weapon attack ─────────────────────────────────────────────
  // Independent of the Weave gestures above: this is its own rebindable key
  // (default Q), aimed with the mouse, and it never consumes or suppresses a
  // weave action. The attempt is made every frame the key is held; the
  // weapon's own cooldown decides whether an attack actually starts.
  if (inputState.isWeaponAttackHeldFlag) {
    const weaponPlayer = world.clusters[0];
    if (weaponPlayer !== undefined && weaponPlayer.isPlayerFlag === 1 && weaponPlayer.isAliveFlag === 1) {
      const aim = screenToWorld(
        inputState.mouseXPx, inputState.mouseYPx,
        offsetXPx, offsetYPx, zoom,
        canvas.width, canvas.height,
        virtualWidthPx, virtualHeightPx,
      );
      tryStartPlayerWeaponAttack(world, weaponPlayer, aim.xWorld, aim.yWorld, world.rng);
    }
  } else {
    // Staves channel while the key is held; releasing must stop the drain.
    releasePlayerWeaponAttack(world);
  }

  return { moveDx, jumpTriggered, openPause, interactTriggered, interactInputPulseTrigger, grappleFireTriggered };
}
