export enum CommandKind {
  MovePlayer = 0,
  ReturnToMap = 1,
  Attack = 2,
  BlockStart = 3,
  BlockUpdate = 4,
  BlockEnd = 5,
  Jump = 6,
  GrappleFire = 7,
  GrappleRelease = 8,
  Interact = 9,
  /** Activate the equipped primary Weave (left click quick release). */
  WeaveActivatePrimary = 10,
  /** Begin holding the primary Weave (left click sustained). */
  WeaveHoldPrimary = 11,
  /** Release/end the primary Weave hold. */
  WeaveEndPrimary = 12,
  /** Activate the equipped secondary Weave (right click quick release). */
  WeaveActivateSecondary = 13,
  /** Begin holding the secondary Weave (right click sustained). */
  WeaveHoldSecondary = 14,
  /** Release/end the secondary Weave hold. */
  WeaveEndSecondary = 15,
  ToggleFullscreen = 16,
  /** Open the world map (read-only unless at a save tomb). */
  OpenMap = 17,
  /**
   * Trigger a zip toward the current grapple anchor.
   * Only has effect when a grapple is already attached (isGrappleActiveFlag === 1).
   * Generated by right mouse button press; Shield Weave handles the held input
   * when no grapple is active.
   */
  GrappleZip = 18,
  /** Advance the current dialogue entry (Enter or E key, left mouse click). */
  AdvanceDialogue = 19,
  ShieldWeaveHold = 20,
  ShieldWeaveEnd = 21,
  /** Open the inventory screen (equipment + carried items). */
  OpenInventory = 22,
}

export interface MovePlayerCommand {
  kind: CommandKind.MovePlayer;
  dx: number;
  dy: number;
}

export interface ReturnToMapCommand {
  kind: CommandKind.ReturnToMap;
}

export interface AttackCommand {
  kind: CommandKind.Attack;
  /**
   * Attack aim point in screen space (absolute pixels).
   * On PC this is the mouse cursor position; on mobile it is the touch-release position.
   * gameScreen.ts converts this to a world-space direction relative to the player.
   */
  aimXPx: number;
  aimYPx: number;
}

export interface BlockStartCommand {
  kind: CommandKind.BlockStart;
  /**
   * Absolute screen-space aim position (pixels).
   * gameScreen.ts converts to world-space direction relative to the player.
   */
  aimXPx: number;
  aimYPx: number;
}

export interface BlockUpdateCommand {
  kind: CommandKind.BlockUpdate;
  /**
   * Absolute screen-space aim position (pixels).
   * gameScreen.ts converts to world-space direction relative to the player.
   */
  aimXPx: number;
  aimYPx: number;
}

export interface BlockEndCommand {
  kind: CommandKind.BlockEnd;
}

export interface JumpCommand {
  kind: CommandKind.Jump;
}

export interface GrappleFireCommand {
  kind: CommandKind.GrappleFire;
  /**
   * Aim point in screen space (absolute pixels) where the hook is fired.
   * gameScreen.ts converts to world-space anchor position.
   */
  aimXPx: number;
  aimYPx: number;
}

export interface GrappleReleaseCommand {
  kind: CommandKind.GrappleRelease;
}

export interface InteractCommand {
  kind: CommandKind.Interact;
}

/** Activate primary Weave — burst-type (left click quick release). */
export interface WeaveActivatePrimaryCommand {
  kind: CommandKind.WeaveActivatePrimary;
  aimXPx: number;
  aimYPx: number;
}

/** Hold primary Weave — sustained-type (left click held). */
export interface WeaveHoldPrimaryCommand {
  kind: CommandKind.WeaveHoldPrimary;
  aimXPx: number;
  aimYPx: number;
}

/** End primary Weave hold. */
export interface WeaveEndPrimaryCommand {
  kind: CommandKind.WeaveEndPrimary;
}

/** Activate secondary Weave — burst-type (right click quick release). */
export interface WeaveActivateSecondaryCommand {
  kind: CommandKind.WeaveActivateSecondary;
  aimXPx: number;
  aimYPx: number;
}

/** Hold secondary Weave — sustained-type (right click held). */
export interface WeaveHoldSecondaryCommand {
  kind: CommandKind.WeaveHoldSecondary;
  aimXPx: number;
  aimYPx: number;
}

/** End secondary Weave hold. */
export interface WeaveEndSecondaryCommand {
  kind: CommandKind.WeaveEndSecondary;
}

export interface ToggleFullscreenCommand {
  kind: CommandKind.ToggleFullscreen;
}

export interface OpenMapCommand {
  kind: CommandKind.OpenMap;
}

/** Open the inventory screen. */
export interface OpenInventoryCommand {
  kind: CommandKind.OpenInventory;
}

/** Trigger a zip toward the current grapple anchor (right mouse press). */
export interface GrappleZipCommand {
  kind: CommandKind.GrappleZip;
}

/** Advance the dialogue overlay to the next entry (Enter / E / left click). */
export interface AdvanceDialogueCommand {
  kind: CommandKind.AdvanceDialogue;
}

export interface ShieldWeaveHoldCommand {
  kind: CommandKind.ShieldWeaveHold;
  aimXPx: number;
  aimYPx: number;
}

export interface ShieldWeaveEndCommand {
  kind: CommandKind.ShieldWeaveEnd;
}

export type GameCommand =
  | MovePlayerCommand
  | ReturnToMapCommand
  | AttackCommand
  | BlockStartCommand
  | BlockUpdateCommand
  | BlockEndCommand
  | JumpCommand
  | GrappleFireCommand
  | GrappleReleaseCommand
  | InteractCommand
  | WeaveActivatePrimaryCommand
  | WeaveHoldPrimaryCommand
  | WeaveEndPrimaryCommand
  | WeaveActivateSecondaryCommand
  | WeaveHoldSecondaryCommand
  | WeaveEndSecondaryCommand
  | ToggleFullscreenCommand
  | OpenMapCommand
  | OpenInventoryCommand
  | GrappleZipCommand
  | AdvanceDialogueCommand
  | ShieldWeaveHoldCommand
  | ShieldWeaveEndCommand;
